# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dnl-YvEZ8hyIyRF4skUJZmuqSdbzn7C9

TASK 1:Prediction using Supervised Machine Learning
"""

import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn import metrics

"""step1: **importing data**"""

url="http://bit.ly/w-data"
data=pd.read_csv(url)
print("Data imported successfully")
data.head(10)

data.shape

data.info()

"""step2: **Input data Visualization**"""

data.plot(x='Hours',y='Scores',style='o')
plt.title('Hours vs Percentage')
plt.xlabel('Hours Studied')
plt.ylabel('Percentage Score')
plt.show()

"""step3:**Data Preprocessing**"""

x=data.iloc[:,:-1].values
y=data.iloc[:,1].values

"""step4:**Training the Algorithm**"""

x_train, x_test, y_train, y_test =train_test_split(x,y,test_size=0.2,random_state=0)
regressor=LinearRegression()
regressor.fit(x_train.reshape(-1,1),y_train)
print("Training complete")

line=regressor.coef_*x+regressor.intercept_
plt.scatter(x,y)
plt.plot(x,line,color='red');
plt.show()

"""**Checking the accuracy scores for training and test set**"""

print('test score')
print(regressor.score(x_test,y_test))
print('training score')
print(regressor.score(x_train,y_train))

y_test

y_pred = regressor.predict(x_test)
y_pred

data= pd.DataFrame({'Actual': y_test,'Predicted': y_pred[:5]})
data

print("Score of student who studied for 9.25 hours a dat",regressor.predict([[9.25]]))

"""**model evaluation metrics**"""

print('mean absolute error',metrics.mean_absolute_error(y_test,y_pred))
print('mean squared error',metrics.mean_squared_error(y_test,y_pred))